name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{vars.MYSQL_PASSWORD}}
          MYSQL_DATABASE: ${{vars.MYSQL_DATABASE}}
        ports: 
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Setup Environment Variables
      run: |
        touch .env
        echo "MYSQL_DATABASE=${{vars.MYSQL_DATABASE}}" >> .env
        echo "MYSQL_PASSWORD=${{vars.MYSQL_PASSWORD}}" >> .env
        echo "MYSQL_USER=${{vars.MYSQL_USER}}" >> .env
        cat .env

    - name: Set up MySQL
      run: |
        until mysql -hlocalhost -uroot -p${{vars.MYSQL_PASSWORD}} -e ""; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Connect to MySQL
      run: |
          mysql -hlocalhost -uroot -p${{vars.MYSQL_PASSWORD}} -e "SHOW DATABASES;"

    - name: Install dependencies
      run: npm install

    - name: Run Integration Tests
      run: npm test
