name: integration-test

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
                    MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
                    MYSQL_USER: ${{ secrets.MYSQL_USER }}
                    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: "18"

            - name: Install dependencies
              run: npm install
              

            - name: Run Tests
              run: npm test
              env:
                MYSQL_USER: ${{ secrets.MYSQL_USER }}
                MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
                MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}