name: integration-test

on:
    pull_request:
      branches:
        - main

jobs:  
    build:
      name: CI
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js  
        uses: actions/setup-node@v2
        with:
          node-version: 14
  
      - name: Install dependencies
        run: npm install
  
      - name: Display .env file
        run: |
          echo "MYSQL_USER=root" >> .env
          echo "MYSQL_PASSWORD=anshul" >> .env
          echo "MYSQL_DATABASE=cloud_local" >> .env
          echo "PORT=3306" >> .env
          cat .env
  
      - name: configuremysql
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql
          sudo systemctl status mysql
          mysqladmin -u root password "${{ secrets.MYSQL_PASSWORD }}"
          mysql -u root -p "${{ secrets.MYSQL_PASSWORD }}" -e "CREATE DATABASE  cloud_local;"
  
      - name: Run Tests
        run : npm test
